import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Nav from "@/components/nav";
import createClient from "@/lib/supabase/server";
import { UserProvider } from "@/context/user-context";
import { ToastProvider } from "@/context/toast-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TourIt",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let profile = null;

  if (user) {
      const { data } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', user.id)
          .single(); //single() ensures we get one record, not an array
      profile = data;
    }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider user={user} profile={profile}>
          <ToastProvider>
            <Nav />
            {children}
          </ToastProvider>
        </UserProvider>
      </body>
    </html>
  );
}
